### ISSUE TITLE
Pick a language

### ISSUE THREAD

**Issue by noamcore** [noamcore/FayzerBot#1]
Pick a language:

- Rust
- Elixir
- Python
- Node w/ Typescript
- Go
- Julia

### Languages with NLP

1. Go - `prose`
2. Python - `nltk`, `Scikit-learn`, `Spacy`
3. Elixir - `penelope`
4. Node - `Natural`

**Comment by renanbastos93** [comment]
Sorry, I don't understand. Do you want to know what language to use in your project?

**Comment by noamcore** [comment]
Haha, yeah, sorry for that. This project is a personal just-for-fun project and to learn new things with that, and some languages listed here are languages that I have interest to learn well (except Julia and Go for now).

**Comment by renanbastos93** [comment]
Hahaha, I understood. But I was going to recommend for you to use Go[Lang] or Node[JS].

**Comment by noamcore** [comment]
I'm choosing Node for this project. :+1:
